### ISSUE TITLE
Report Info

### ISSUE THREAD

**Issue by mohammedabbas27** [renatoathaydes/spock-reports#163]
Hi there, I am new at using Spock-reports and would love to know how do I access the report info(used the method reportInfo("some description about the test case")) as JSP variable in the HTML file

**Comment by mohammedabbas27** [comment]
First of all, thank you for taking your time to address this issue I'm facing.
I have used a method called reportInfo("Some Description") in my groovy test file, I am modifying the report (HTML file ) therefore so how do i fetch the parameter passed to the reportInfo() method, My main objective is to be able to display the test case description in the HTML report, if there is any better way to achieve this I would love to hear your suggestions regarding this. I really hope that I have made myself clear, if not I apologize

Thank You.
ps: I mentioned JSP variable because as I could see JSP scriptlets tag used all over the HTML report file.

**Comment by renatoathaydes** [comment]
> ps: I mentioned JSP variable because as I could see JSP scriptlets tag used all over the HTML report file.

You must be looking at the wrong reports because there's no JSP tags in spock-reports HTML reports.

`reportInfo('Some Description')` does exactly what you think it does: it adds the given String to the report. If you don't see that, you're most likely looking at the wrong reports.

See [this sample](https://codepen.io/renatoathaydes/full/ihGgt) so you know what spock-reports's reports look like by default (maybe you're using a template report?? in which case you need to check which template you're using and make sure you add the information in that as well, as shown in the default [MD template](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/resources/templateReportCreator/spec-template.md)).
