### ISSUE TITLE
Remove println statements in favour of logging framework

### ISSUE THREAD

**Issue by Slugger** [renatoathaydes/spock-reports#22]
I'm attempting to use this extension in a command line application I'm working on.  The println statements throughout are polluting my console window at runtime with no way to suppress.  Would you be willing to replace those println statements with a logging framework (log4j, slf4j, etc.)?  I'll do a pull request if you're willing to merge it, I just don't want to go to the trouble if you'll never accept a pull request that adds a dependency.

Alternatively, a config option or system property to suppress the println statements would be the next best option.  A logging framework means other users can more easily control what output goes where.

**Comment by renatoathaydes** [comment]
You guessed it... Nobody wants a little extension to their test framework to add yet another dependency to their tests and possibly introduce classpath issues.

However, I agree the printlns should be optional. I would appreciate if you could make the printlns optional (and the default should probably be silent). And of course, if the printlns are enabled, we should probably print a few more things.... Let me know if you'll do it, otherwise I will do it when I get some free time (probably after week, at least).

**Comment by Slugger** [comment]
Yeah, I'll tackle this; I'm going to try to roll this extension into my app as the reporting mechanism next week at some point so I'll do a PR for this feature.  After this, I think the rest of my mods are going to be a little too radical but I'm hoping to get as much merged into your master as possible so I'm not too far off and can easily merge any changes you make into my fork.

**Comment by Slugger** [comment]
PR #25 has the conversion to `@Log`
