### ISSUE TITLE
Parameter value not showing in the step name

### ISSUE THREAD

**Issue by Sassan-SurePay** [renatoathaydes/spock-reports#226]
Hi there,

I'm trying to refer to parameter name in my step definition e.g. 
when: "I need to see this parameter value #parameterName"

But the parameter value doesn't show in the final report. Please see the screenshots below:

![Screenshot 2022-03-07 at 09 10 34](https://user-images.githubusercontent.com/90700935/156992403-38d87227-1d5d-43dd-acc4-64c1b34fa4e7.png)

![Screenshot 2022-03-07 at 09 11 10](https://user-images.githubusercontent.com/90700935/156992492-154abd08-c24d-4189-94e4-be44542dc4f6.png)

**Comment by renatoathaydes** [comment]
This was working fine in Spock 1, but seems to have stopped working in certain cases in Spock 2.

**Comment by renatoathaydes** [comment]
I think this has to do with `@Unroll` being now the default... when a test is unrolled, did you mark your test with whatever the NOT-unrolled annotation is or it's unrolled?

**Comment by Sassan-SurePay** [comment]
Hi, I have tried with both unrolled and regular versions of the report. The result is the same.

**Comment by renatoathaydes** [comment]
This scenario is included in the tests.

See `com.athaydes.spockframework.report.FakeTest` and the expected reports using in the assertions:

* `src/test/resources/com/athaydes/spockframework/report/internal/FakeTestReport.html`
* `src/test/resources/FakeTest.md`

Only the unrolled case is checked because there is no way to resolve the parameter otherwise, as the block shows up only once and there are potentially many values the block variable could have, so which one should we use?

I tried this spec for manual tests:

```groovy
import spock.lang.Specification
import spock.lang.Unroll

class MySpec extends Specification {

    @Unroll
    def 'check values'( ){
        expect: 'parameter has value #value'
        true

        where:
        value << [1, 2, 3]
    }
}
```

Result:

<img width="1049" alt="Screen Shot 2022-08-25 at 19 23 42" src="https://user-images.githubusercontent.com/1901277/186730186-a58e9a21-b434-44ba-bb98-8fb51f1b16d2.png">

As the tests are passing, there must be something in your environment or tests that is different than the tests are checking.

Can you provide a specification that presents this problem even with an unrolled annotation?

**Comment by renatoathaydes** [comment]
Closing this due to lack of feedback.
