### ISSUE TITLE
Use @Slf4j instead of @Log

### ISSUE THREAD

**Issue by monitorjbl** [renatoathaydes/spock-reports#51]
Java logging is a massive pain to deal with, and SLF4J isn't. Considering that SLF4J can be configured to use Java logging if you so desire, it would be awesome if this utility supported it natively.

This is the line that I'm referring to: https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/SpockReportExtension.groovy#L21.

It causes the following output that has to be handled separately from all other logger types if you are not using Java logging (which fewer and fewer people are nowadays): 

```
Nov 28, 2015 7:23:13 PM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
INFO: Configuring com.athaydes.spockframework.report.SpockReportExtension
Nov 28, 2015 7:23:13 PM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
INFO: SpockReports config loaded: [com.athaydes.spockframework.report.template.TemplateReportCreator.reportFileExtension:md, com.athaydes.spockframework.report.template.TemplateReportCreator.specTemplateFile:/templateReportCreator/spec-template.md, com.athaydes.spockframework.report.IReportCreator:com.athaydes.spockframework.report.internal.HtmlReportCreator, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryTemplateFile:/templateReportCreator/summary-template.md, com.athaydes.spockframework.report.internal.HtmlReportCreator.summaryReportCss:spock-summary-report.css, com.athaydes.spockframework.report.template.TemplateReportCreator.summaryFileName:summary.md, com.athaydes.spockframework.report.internal.HtmlReportCreator.featureReportCss:spock-feature-report.css, com.athaydes.spockframework.report.hideEmptyBlocks:false, com.athaydes.spockframework.report.outputDir:build/spock-reports]
Nov 28, 2015 7:23:13 PM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
INFO: Loading settings for reportCreator of type com.athaydes.spockframework.report.internal.HtmlReportCreator
```

**Comment by renatoathaydes** [comment]
Hi @monitorjbl. The reason I decided to use java.util.logging (JUL) is that it is included in the JRE, so requires no external dependencies.... If I used sfl4j and your project didn't, you would have to include sfl4j  in the classpath just to run your tests with Spock. If you already have sfl4j in the classpath, then your version may conflict with the one spock-reports is using and you may be unable to use spock-reports. Neither problem exists with JUL.

The only drawbacks I can see in using JUL is that is much less powerful and, as you mentioned, requires you to add special configuration if you care about your test logs.

However, this is easy to fix... sfl4j can take JUL log messages so you don't have to handle JUL config: http://www.slf4j.org/legacy.html#jul-to-slf4j

As I believe most users do not care about having JUL log messages in their test logs (but they certainly would care if they got `MethodNotFoundException`s due to incompatibility of sfl4j versions), I think that the current solution is still the best one.

I'm open to discuss further if you think my reasons are not enough.

**Comment by monitorjbl** [comment]
I tried using the JUL-SLF4J bridge and it's not working. I believe it's because initializing it can only happen after your code has only run. I'm not sure how to work around this; your code runs while the Spock extension is being initialized so it's always going to come first.

I think your reasons are good ones, and I definitely understand why you decided to use JUL. The only request I would make then is that these messages have their log level set so they do not show up by default. It's not a big enough deal that they show up to make a sweeping requirement change, it's just annoying.

Would that work for you?

**Comment by monitorjbl** [comment]
Figured I'd make a PR in case what I was talking about was unclear. I tested this locally and it solves my problem pretty well.

**Comment by renatoathaydes** [comment]
I wouldn't mind this, but the reason the log messages were set to `info` is that people writing templates were having a hard time to find out what was happening when something went wrong. I think they were using `sfl4j` for logging and JUL's `fine` does not actually map to any level in `sfl4j` so they never see anything.

I will see if I can write a test that uses the JUL-sfl4j bridge, then remove the messages by config... if I cannot do that I will accept your PR. Otherwise I will add a note in the docs about how to disable those messages.

**Comment by monitorjbl** [comment]
@renatoathaydes Any update?

**Comment by renatoathaydes** [comment]
I will get back to you tomorrow! Sorry for the delay.

**Comment by renatoathaydes** [comment]
Alright, I've spent hours trying to get JUL turned off but this crap just doesn't work!

I've done what needs to be done:

* set system property `java.util.logging.config.file` to the properties file used to configure JUL.
* configure JUL to log SEVERE only.

In my case, I put this instruction in the Gradle file:

```groovy
test {
    systemProperty 'java.util.logging.config.file', "${project.projectDir.absolutePath}/jul.properties"
```

And I put the properties file in that location with this contents:

```properties
.level=SEVERE
```

As far as I know, this should've worked... I printed the system property from the spock-reports code, and it is seen with the correct value... JUL just seems to ignore that file... freaking stupid logging...

If I can't make it work in the next few days, I will get rid forever of this stupid JUL logging and use sfl4j.

**Comment by monitorjbl** [comment]
Yeah, JUL is a huge pain to deal with. I want to say, "Good luck!" but I really hope you switch to SLF4J :) 

If it's any help, you only need a hard dependency on the slf4j-api library. If someone is using Maven/Gradle and has a conflict, it's pretty trivial to exclude that transitive dependency from your library.
