### ISSUE TITLE
Inline styles causing CSP violations

### ISSUE THREAD

**Issue by kfraczek** [renatoathaydes/spock-reports#54]
In both feature and summary reports all styles are inlined in the html code. In some cases this raises Content Security Policy violations which prevent the styles from being displayed. Setting `com.athaydes.spockframework.report.internal.HtmlReportCreator.summaryReportCss` / `.featureReportCss` doesn't help - the content of the provided css file simply gets inlined.

Would really appreciate to see this fixed (writing the issue instead of creating a pull request as per the readme file). Keep up the good work :)

Edit: This of course only happens when Content Security Policy is enabled on the target website, so it won't be noticed by everyone (especially while opening the files locally). It's still a pain when working in strict security enviroment though.

**Comment by renatoathaydes** [comment]
Reports are not websites. Using inline css makes it possible for reports a one-file entity, which in my opinion is what they should be.

When you say you would like to see this fixed, I think you assume something is broken, but I can't see how inlining CSS is something that is broken.

Is there any alternative way to make your browser not show a warning?

**Comment by kfraczek** [comment]
The only way to make it work would be relaxing the policies (unfortunately not doable in my case) or making the css a separate file.

Fix was indeed not the best word. I meant it more as a feature request, A disabled by default option to copy the provided css file over and include it instead of inlining would solve my problems.

**Comment by renatoathaydes** [comment]
Ok, I can see how that may be useful.. I will add an option to use css as a link to an external resource... that should *fix* it :)

**Comment by renatoathaydes** [comment]
@kfraczek could you please have a look at the latest commit where I documented this new feature and see if that's good for you?

In brief: if you set the `inlineCss` property to false, instead of inlining the css in the html file, a css file will be created in the `outpuDir` and a link to it will be added to the html file.
The location of the css resource can be set to a classpath resource or to a URL (but the resource is always copied to a local file... I could make it point to the actual location of the css resource and not copy it locally, not sure if that's better... could be an extra option).

**Comment by kfraczek** [comment]
This is exactly what I need, thanks a ton :)

**Comment by renatoathaydes** [comment]
This code is release in version 1.2.9 on both Maven Central and JCenter!
