### ISSUE TITLE
Template Reports don't display the full stack trace

### ISSUE THREAD

**Issue by dpost** [renatoathaydes/spock-reports#66]
It appears that the default html report creator now has an option to print the full stack trace but that parameter doesn't appear to be used in the TemplateReport creator. Do you plan to add that functionality to the template reports as well?

**Comment by renatoathaydes** [comment]
This is not necessary because templates can add the stacktraces themselves if wanted.

In a template, you have access to the `data` variable which contains an instance of [SpecData](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/internal/SpecData.groovy).

Each `FeatureRun` in `featureRuns` contains a `failuresByIteration` property which you can use to add the stacktrace to the template.

See [ProblemBlockWriter](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/internal/ProblemBlockWriter.groovy) to see how the HTML reports use that to include the stacktrace in the report.
