### ISSUE TITLE
Exception when spock fails to initialize spec

### ISSUE THREAD

**Issue by bmsq** [renatoathaydes/spock-reports#68]
We have some data driven Spock Specifications which create database connections during startup and use the "@Shared" annotation:
`
class ExampleSpec extends Specification {
	@Shared db = createDatabaseConnection()
}
`

If an exception is thrown during initialization, SpecInfoListener.error() is triggered.  Unfortunately, this produces a null pointer exception because SpecInfoListener.beforeSpec() is never called:

> java.lang.NullPointerException: Cannot get property 'featureRuns' on null object
> 	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
> 	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:169)
> 	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
> 	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.callGroovyObjectGetProperty(GetEffectivePogoPropertySite.java:62)
> 	at com.athaydes.spockframework.report.SpecInfoListener.currentRun(SpockReportExtension.groovy:170)
> 	at com.athaydes.spockframework.report.SpecInfoListener.dummySpecIteration(SpockReportExtension.groovy:177)
> 	at com.athaydes.spockframework.report.SpecInfoListener.error(SpockReportExtension.groovy:155)
> 	at org.spockframework.runtime.MasterRunListener.error(MasterRunListener.java:64)
> 	at org.spockframework.runtime.JUnitSupervisor.error(JUnitSupervisor.java:99)
> ....

The testing suite was going to fail anyway but the exception from Spock Reports is preventing the real exception from appearing in the logs.

My gut feeling is that this sort of error should be ignored by Spock Reports as the error isn't actually associated with a Spec.  

Pull request to follow.

**Comment by tilmanginzel** [comment]
Hey,

I came across the same issue but unfortunately this fix does not seem to work properly. Take the following spec as an example:

```groovy
class NullPointerSpec extends Specification {
    @Shared def x = value()

    def "feature"() {
        expect:
        true
    }

    def value() {
        assert 1 == 2
    }
}
```

If I run the spec, the `NullPointerException` is gone (that's ok), but the report will not be created. `aggregated_report.json` is empty.

In addition, rather than hiding exceptions while initializing the spec, it would be great if it is possible to see those too. They could provide necessary information on why other features failed, and it makes debugging much easier. For example, IntelliJ shows a "Class Configuration" test with the exception, and Gradle Test Reports show a "classMethod" test. 

Maybe we could use the `dummySpecIteration` to solve this. If you like, I could try to provide another pull request for this.

**Comment by renatoathaydes** [comment]
It's good to have another example of the issue. I will try to fix it today.

**Comment by tilmanginzel** [comment]
Awesome, thanks in advance! I had another idea: Instead of creating a `dummyFeature`, maybe you could add the exception messages directly to the `SpecData`, so they would result in a new field at the corresponding specification in the `aggregrated_report.json`. Then there would be more possibilities to render those in a custom template.

**Comment by renatoathaydes** [comment]
Breakthrough! Did a little reverse engineering to get the data necessary create the report. Here's the report for the `BrokenSpec` above!

<img width="865" alt="screen shot 2016-06-07 at 21 12 44" src="https://cloud.githubusercontent.com/assets/1901277/15871415/d4f138c0-2cf4-11e6-9d94-3b627f055333.png">

**Comment by tilmanginzel** [comment]
Great to see! The execution took quite some time. :P
The only thing I do not like so much about this solution, is that the error message is added to the first feature, even if it is not directly related to it. Any idea how to change that?

**Comment by renatoathaydes** [comment]
> The only thing I do not like so much about this solution, is that the error message is added to the first feature

Yep, you're right... any other features in the spec are shown as ignored. I will have to do more work to fix that.

**Comment by renatoathaydes** [comment]
<img width="846" alt="screen shot 2016-06-07 at 22 21 11" src="https://cloud.githubusercontent.com/assets/1901277/15873276/3774483a-2cfe-11e6-882f-1da3ee93db6b.png">

If I do not show all features, I will break compatibility with report templates and the changes will be much harder. I think there's no reason to do that unless the current solution really sucked, which I think it doesn't.

All features are shown, only the first one as error, the rest as ignored, but that's because that's exactly what happened (almost, because the first feature does not really start). But the big message `[SPEC INITIALIZATION ERROR]` should be enough to make it really clear what happened.

If you need the Exception stacktrace, there's already a config option to enable showing that, and it will work fine.

**Comment by tilmanginzel** [comment]
> I think there's no reason to do that unless the current solution really sucked, which I think it doesn't.

No it doesn't, this should be perfectly fine to work with. Thank you very much for the fast fix, I will try it out today. Do you know when you will release the next version?

**Comment by renatoathaydes** [comment]
There's one more bug to fix before I can release. The other bug is easier.

I also want to try to make all features count as ERROR when this issue happens.

So, I think one, or maybe a few days, and I can release.

**Comment by tilmanginzel** [comment]
Ok, no hurries! I found a new bug (maybe it's the one you already know).
```groovy
class BrokenSpec extends Specification {
    def "success"() {
        expect:
        true
    }

    def "failure"() {
        expect:
        false
    }
}
```

Result:
![brokenspec](https://cloud.githubusercontent.com/assets/3899565/15886829/56162036-2d5f-11e6-8447-34935f24c4aa.png)

**Comment by renatoathaydes** [comment]
hehe, yep that's bad... the tests are still failing, so yeah, I have more fixes to do.

**Comment by renatoathaydes** [comment]
Alright, fixed that. Also I think this looks better (first feature shows the error that caused the initialization error, next features show a dummy Exception without a stacktrace to avoid repeating the same thing.... all features are shown as having an error, not ignored anymore):

<img width="868" alt="screen shot 2016-06-08 at 19 32 14" src="https://cloud.githubusercontent.com/assets/1901277/15904142/1d3556f0-2db0-11e6-819e-5b37d9d74d7b.png">

**Comment by renatoathaydes** [comment]
@tilmanginzel I believe this is now ready for a release. I will fix an unrelated bug now. Please tell me if you have time to check this.

**Comment by tilmanginzel** [comment]
Seems to be working as expected now, thanks!
