### ISSUE TITLE
NullPointerException: Cannot get property 'className' on null object

### ISSUE THREAD

**Issue by tilmanginzel** [renatoathaydes/spock-reports#75]
Hey, I found another bug. If an initialization error occurs in a super class while executing a child specification, a `NullPointerException` is thrown in `HtmlReportCreator` and `TemplateReportCreator` in the following line. As a result the report is not created.

```groovy
def specClassName = data.info.description.className
```

Example:
```groovy
class SuperSpec extends Specification {
    @Shared def x = 1/0
}

class ChildSpec extends SuperSpec {
    def "feature"() {
        expect:
        true
    }
}
```
----
Proposed fix:
Replace all `data.info.description.className` occurrences with something like this:

```groovy
def specClassName = data.info.description?.className
if (specClassName == null) {
    specClassName = data.info.subSpec?.description?.className
}
```
We could create a `Utils.getSpecClassName(SpecData data)` method, because the description is called in various different places. This fix seems to work and if you agree I can provide another pull request.

**Comment by renatoathaydes** [comment]
The bug here seems to be in Spock... but yeah, we'll have to find a good workaround. Your suggestion seems good, but I wish we didn't have to jump through hoops to get information from specs like this... let me have a look at this in the next few days. I am going on vacation today, but I should have some time to dedicate to spock-reports.

**Comment by tilmanginzel** [comment]
Yes of course, take your time! ;)
