### ISSUE TITLE
Add support for issueUrlPrefix for @Issue

### ISSUE THREAD

**Issue by tjuchniewicz** [renatoathaydes/spock-reports#76]
In `@Issue` we want to write only ID of the issue for example `@Issue("SP-1234")`. 

To support this we need to add configuration property `issueUrlPrefix`. Something similar to Spock implementation [IssueExtension](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IssueExtension.java).

Or maybe there is a possibility to use `IssueExtension` in spock-reports?

**Comment by renatoathaydes** [comment]
`IssueExtension` is a built-in, so yes, we can add support for that!

**Comment by tjuchniewicz** [comment]
What is an idea to support this? Parse [`@Issue`](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/spock/lang/Issue.java) for `@ExtensionAnnotation` and execute extension implementation class for example [IssueExtension](https://github.com/spockframework/spock/blob/master/spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IssueExtension.java) ? Or maybe reimplement extension implementation class in spock-reports?

 If you give me some hints I will try to prepare PR.

**Comment by renatoathaydes** [comment]
The `HtmlReportCreator` finds the `@Issue` and `@See` annotations and processes them [here](https://github.com/renatoathaydes/spock-reports/blob/next/src/main/groovy/com/athaydes/spockframework/report/internal/HtmlReportCreator.groovy#L315). If the value of the annotation looks like a URL, the HTML report will contain a link with the URL, otherwise it just creates a span with plain text.

From what I saw in the `IssueExtension` class, it takes the annotation value and adds it as a Tag to the SpecElement... If we can get that Tag, maybe we can make the spock-reports code read that Tag instead of the annotation, so all the config for this will work (if the Tag does not exist, it may just keep doing what it's doing now).

If you decide to give it a shot, just checkout the `next` branch instead of `master` and make the PR against `next` (next release).

Thanks!

**Comment by tjuchniewicz** [comment]
OK. I will try.

**Comment by tjuchniewicz** [comment]
There is an issue with `@Issue`: https://github.com/spockframework/spock/issues/619

**Comment by renatoathaydes** [comment]
Yes, that extension's code is far too simplistic... Make a PR to change that... maybe steal the code from this project's `Utils.isUrl()` :)

**Comment by tjuchniewicz** [comment]
Enhancement implemented in my private branch https://github.com/ebjwc/spock-reports/commit/d8b301f760b98d89005418a6e8043c65fd46715d 

Waiting for spock fix.

**Comment by tjuchniewicz** [comment]
spockframework/spock#619 fixed.

**Comment by tjuchniewicz** [comment]
Waiting for Spock 1.1 to be released.

**Comment by tjuchniewicz** [comment]
Because Spock 1.1 is available now I will provide PR for current codebase.
