### ISSUE TITLE
Is it possible to use HTML-reports AND template-reports?

### ISSUE THREAD

**Issue by mfuerstenau** [renatoathaydes/spock-reports#79]
Is it possible to use HTML-reports AND template-reports at the same time?

**Comment by renatoathaydes** [comment]
Only one report creator can be configured. But you may be able to call on the html reportCreator from your template, which would allow you to create both reports...

**Comment by renatoathaydes** [comment]
To contributors: I think this feature could actually be quite useful as some people might prefer HTML reports, others the MD reports :) Why not generate both if desired!?

I would suggest allowing the config file to take the name of the classes that should generate reports as a comma-separated String (currently only one class can be specified), then, in the `com.athaydes.spockframework.report.internal.ConfigLoader` class, load all classes so that the `com.athaydes.spockframework.report.SpockReportExtension` can use more than one report creator!

**Comment by SimonWatts** [comment]
Hi - I've had a go at fixing the above - take a look and see what you think

**Comment by renatoathaydes** [comment]
Sorry for the delay releasing this, but finally, this is included in the 1.4.0 release which I just pushed!
Thanks a lot.
